server_port: 8080


models:
  ai:         'mistral'
  classifier: 'qwen2.5:0.5b'
  max_chars_per_block: 4000


db:
  host: 'localhost'
  name: 'CUCINA'
  user: 'root'
  pass: ''


ip:
  worker: '192.168.15.5'
  master: '192.168.15.8'
  default: '127.0.0.1'



